version: "3"

services:
  spiti-jenkins:
    image: spiti-jenkins:latest
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "8910:8910"
    container_name: "spiti-jenkins_latest"
